### ISSUE TITLE
Vuex dependecy BC break

### ISSUE THREAD

**Issue by camohub** [ElMassimo/vuex-stores#19]
I have a Nuxt project which uses your vuex-stores library. Today I made some changes in package.json and find out that there are some BC breaks in the Vuex dependency. It seems it is caused by your version signature which says 
```
  "dependencies": {
    "vuex": ">2.0"
  },
```
This downloads me the Vuex repository of version: "4.0.2", 

This contains the code 
```
  store._state = vue.reactive({
    data: state
  });
```
in vuex.cjs.js which throws me an error 
**vue.reactive is not a function**

I dont know if I have right but if yes, could you fix it please? Thanks a lot.

**Comment by ElMassimo** [comment]
Hi @camohub, thanks for reporting!

The dependency requirement should have been more strict:

```json
  "dependencies": {
    "vuex": "~>3"
  },
```

Unfortunately, I can't unpublish the package. To fix the problem, make sure to lock `vuex` to version 3.

---

Also, as mentioned in the README:

> Prefer [pinia](https://github.com/posva/pinia) if using Vue 3 or `@vue/composition-api` in Vue 2

You can continue to use this library and `vuex@3` if you don't want to upgrade though.

**Comment by camohub** [comment]
How can I lock vuex on version 3? Your library decide which version will be downloaded. Is there a maner how to do it in package.json. I dont know. 

I thing you should release two new versions. One for Vuex 3 and one for Vuex 4. 
This is BC break.

**Comment by kissu** [comment]
@camohub lock the version of Vuex in your `package.json`, `vuex-stores` looks totally fine tbh. 👌🏻

**Comment by camohub** [comment]
Ok I have it. Thanks a lot. Have nice day.
