### ISSUE TITLE
Support for Typescript

### ISSUE THREAD

**Issue by chenxeed** [ElMassimo/vuex-stores#2]
Hi!

This is a great library and I foresee it will help a lot when writing component with Vue Composition API.

Is there a plan to add the typing interface as well in the script?

Thank you!

**Comment by ElMassimo** [comment]
Hi! Thanks for checking it out!

No plans yet, but would be willing to accept pull requests to add typings.

In the meantime, I'd encourage you to check similar options that were designed for TypeScript, such as [`vuex-typed`](https://github.com/owlsdepartment/vuex-typed).
